# -*- coding: utf-8 -*-
txt = {
	"brief" : [
	u"Liefste Katrien,",
	u"",
	u"Zo vaak herinner ik me die lange uren op kantoor, omringd door lege zakjes chips, chocoladerepen - kleine porties troost - maar giechelend om wie we waren en wat we deden. En als we tegen valavond aan glunderend zeiden, 'Dit is het moment!', onze computers afsloten, onze ogen bijschilderden, een licht drupje parfum in onze halzen sproeiden en arm in arm naar de cinema liepen, dan werd onze spraakwaterval pas gesmoord wanneer de film op dreef kwam en onze naïeve zielen met grote gulzigheid opslorpte.",
	u"Op een van die avonden, weet je nog, stelde je voor dat wij, wanneer al onze liefdes zijn heengegaan en we eenzaam thuis zitten te kniezen, onze oude dagen zouden organiseren in hetzelfde rusthuis.",
	u"Hier zit ik, in het gezelschap van een robot die als een vriend tegen me praat, met een zoetgevooisde mannenstem die ik zelf kan aanpassen. Ik zou hem zelfs jouw timbre kunnen geven, als je hem eventjes zou willen trainen. Anderen gamen een hele dag met die robot. Ze laten kreetjes wanneer ze een kilowatt elektriciteit hebben opgewekt, of weer eens een stuk land van zee hebben teruggewonnen. En als het spel over is, vallen hun oogleden dicht. Ik heb die spelkracht niet meer, maar mijn lippen lopen nog over van woorden als ik aan jou denk.",
	u"Liefste Katrien, ik zit voor een raam dat uitgeeft op een miezerige herfsttuin. De bomen zijn leeggewaaid, op dat ene blad na, dat het hardnekkig volhoudt in de strakke wind. Vooraleer dat blad van de eik is gerukt, wil ik je aan je voorstel herinneren.",
	u"Dit is een luxe-rusthuis, gerund door boeddhisten voor wie de dood slechts een overgang betekent. Dag in dag uit zouden we samen koffie kunnen drinken en, onder het mom van een spelletje Scrabble, herinneringen ophalen aan onze bazen, de stad, onze collega's, die oude verwoestende liefdes die nooit wilden wat wij wilden. Jij zou Radio 2 opzetten en ik zou mopperen, want die radio is toch zo regionaal. En al onze zorgen zouden weer mogen bestaan. Een gebroken hak, een printer die het niet meer doet, een verkoper die ons heeft opgelicht, een man die zijn beloftes niet is nagekomen, ze zouden nu ingegroeide teennagels worden, pijnlijke darmen, slapeloosheid. Maar het zou geen verschil maken, toch?",
	u"Ik vraag je dus, met deze Valentijn, lieve vriendin, of je het zou zinnen om hier te komen wonen. Please, beslis snel, de koffie staat al klaar! Zonder melk, zonder suiker.",
	u"",
	u"Liefs,",
	u"Anja",
	],
	"gedicht" : [
	u"Je vraagt me om te kiezen",
	u"één gewoonte uit die duizenden gewoontes",
	u"die we samen elke dag opnieuw",
	u"als vanzelf bij elkaar heruitvinden",
	u"een lichte aai op je wang in de ochtend",
	u"de koffie die jij voor me uitschenkt",
	u"ik de afwas, jij de vuilbakken",
	u"en zo gaat het een heel leven door",
	u"de kleine rituelen van ons bestaan ",
	u"niet één wil ik vergeten dat niet zichzelf vergeet",
	u"maar jij vraagt me om te kiezen",
	u"laat het dan die kleine routine zijn",
	u"die we onze jardinage hebben gedoopt",
	u"jij en ik aan een tafeltje bij het raam",
	u"in een café in de stad",
	u"koffie, thee, bier, wijn en soms ook rum",
	u"waarmee we de scheut van onze ontmoeting tot een plant hebben doen uitgroeien",
	u"waarmee we rotte bladeren afbranden",
	u"en een roos in de knop besprenkelen",
	u"en kijk hoe ze ontluikt",
	u"tussen alle praktische beslommeringen van ons leven door.",
	u"Zullen we nog een keer?",
	u"Jij een beetje wieden, ik wat sproeien?",
	],
	"verhaal" : [
	u"Op 23 augustus 2009 schoof Alia het gordijn opzij en keek tegen een staalblauwe hemel aan. Het beloofde een hete dag worden, al de vijfde op rij. Een kind spetterde water op het balkon, haar overbuur rookte een sigaret uit het raam, een vrouwenhand streelde zijn borst. De lucht vroeg erom te worden bezongen en bemind, maar Alia kon wel huilen. ",
	u"Met opgetrokken benen in de sofa sprak ze zichzelf moed in, dat alleen leven ook wel ok is, dat ze nog maar dertig is, dat ze haar koffie zelf moet zetten, maar wel mag kiezen wanneer, dat ze een bad kan nemen, daar mag mokken tegen de hele wereld, en weer in bed mag kruipen als ze dat zo voelt. Zélfs al was het de mooiste dag van het jaar, zij bezat het recht om die uit te roepen tot de Dag van de Verschrikkelijke. Met dat gevoel van absolute vrijheid liet ze het bad vollopen. Ze ging wel tien keer kopje onder in de hoop dat de binnenkant van haar hoofd zou worden meegewassen. ",
	u"In een baan van kleine druppeltjes keerde ze terug naar de living. Ze plofte in de sofa, stond weer op en wriemelde met haar tenen. Zou het de zon zijn die de muren druk maakt, of is het zo dat hitte de bakstenen doet uitzetten? Ze wist het niet, maar als ze niet van haar stokje wilde draaien, moest ze naar buiten. Rok, shirt, sleffers, krant, sleutels, portefeuille, met lange natte haren liep ze naar beneden, de zinderende straat op. Bij het eerste terras vond ze een plekje. Een man die twee tafeltjes verder een krant las, knikte haar toe. Alia glimlachte beleefd terug, lichtjes geschrokken dat ze op dit uur werd herkend. Ze bestelde koffie, las de koppen op de voorpagina, vergat ze meteen, las ze opnieuw en nog eens. Die man had ze al eerder gezien, maar waar? Alia spiedde opzij, maar ai, betrapt, ook hij keek op. ",
	u"'Wij hebben elkaar al eens ontmoet,' stotterde ze, 'maar het spijt me zeer, ik weet echt niet meer hoe of waar.' Ze kleurde hoogrood, zich nu pas bewust van het torenhoge cliché waarmee ze hem had aangesproken.",
	u"'Ik kan het me ook niet meer herinneren,' zei hij verontschuldigend. ",
	u"Ze nipte van haar koffie. Ach wat, als hij het ook niet meer wist. Een reportage over samengestelde gezinnen trok haar aandacht. Halverwege, ter hoogte van 'In vijf jaar tijd steeg het aantal eenoudergezinnen met 12%', vulden de witruimtes zich met het beeld van de man, zijn energieke ogen, aan tafel tijdens een verjaardagsfeest. ",
	u"'Ik weet het weer,' zei ze langs de andere tafeltjes heen tegen de man. 'We spraken elkaar bij Leen en Tom in Antwerpen.' ",
	u"'Ja, dat is het. Zo lang geleden.' Alia sloeg een pagina van de krant om. Na een korte stilte vroeg hij: 'Ken je hen goed?' ",
	u"'Het zijn vrienden van vrienden.' ",
	u"'Ze hebben pas een baby.' ",
	u"'Dat hoorde ik ook.' ",
	u"'En waar hou jij je alweer mee bezig?' ",
	u"",
	u"Het werd moeilijk om de langer wordende zinnen tussen de ruggen van de andere terrasbezoekers te sturen, dus vroeg Alia voorzichtig of Gert niet wilde bijschuiven. Drie uur later keerde ze terug naar haar flat, roodverbrand en smoorverliefd. Hij was grootstedelijk, scherp en single. Het duurde nog een vol jaar voor het iets werd tussen hen. Alia geloofde niet in liefde op het eerste gezicht.",
	],
}
